name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Core
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/metrics.core.svg # FILENAME
          use_prebuilt_image: true
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: commit
          committer_branch: master
          committer_message: "chore: update metrics"
          retries: 3
          retries_delay: 300
          retries_output_action: 5
          retries_delay_output_action: 120
          optimize: css, xml
          config_timezone: Asia/Tashkent
      # Plugins
      - name: Isocalendar
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/metrics.plugin.isocalendar.svg # FILENAME
          base: ""
          use_prebuilt_image: true
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: commit
          committer_branch: master
          committer_message: "chore: update metrics - isocalendar"
          retries: 3
          retries_delay: 300
          retries_output_action: 5
          retries_delay_output_action: 120
          optimize: css, xml
          config_timezone: Asia/Tashkent
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/metrics.plugin.languages.svg # FILENAME
          base: ""
          use_prebuilt_image: true
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: commit
          committer_branch: master
          committer_message: "chore: update metrics - languages"
          retries: 3
          retries_delay: 300
          retries_output_action: 5
          retries_delay_output_action: 120
          optimize: css, xml
          config_timezone: Asia/Tashkent
          plugin_languages: yes
          plugin_languages_details: byte-size, percentage, lines
          plugin_languages_skipped: monyx-nuked/monyx-nuked@hackintosh
          plugin_languages_indepth: true
      - name: Repositories
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/metrics.plugin.repositories.svg # FILENAME
          base: ""
          use_prebuilt_image: true
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: commit
          committer_branch: master
          committer_message: "chore: update metrics - repositories"
          retries: 3
          retries_delay: 300
          retries_output_action: 5
          retries_delay_output_action: 120
          optimize: css, xml
          config_timezone: Asia/Tashkent
          plugin_repositories: yes
          plugin_repositories_featured: monyx-nuked/monyx-nuked, monyx-nuked/meowix # FIXME: change this to your repository
      - name: Topics
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/metrics.plugin.topics.svg # FILENAME
          base: ""
          use_prebuilt_image: true
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: commit
          committer_branch: master
          committer_message: "chore: update metrics - topics" # remember to change these too
          retries: 3
          retries_delay: 300
          retries_output_action: 5
          retries_delay_output_action: 120
          optimize: css, xml
          config_timezone: Asia/Tashkent
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_sort: stars
          plugin_topics_limit: 0
      
